Update default_tools.py to fix a bug on GoogleSearchTool class
the GoogleSearchTool class had an error line 141: super().__init__(self) instead of super().__init__(). I removed the self, which was causing the following issue when using it: 
TypeError: GoogleSearchTool.__init__() got an unexpected keyword argument 'provider'

in the following code: 
model = HfApiModel(
    "Qwen/Qwen2.5-Coder-32B-Instruct", provider="together", max_tokens=8096
)

web_agent = CodeAgent(
    model=model,
    tools=[
        GoogleSearchTool(provider="serpapi"),
        VisitWebpageTool(),
        calculate_cargo_travel_time,
    ],
    name="web_agent",
    description="Browses the web to find information",
    verbosity_level=0,
    max_steps=10,
)

from the multiagent_notebook of the agents course, unit 2.1, Multi-Agent Systems chapter